# Generated by Django 4.2.16 on 2024-09-06 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogue',
            fields=[
                ('CatalogueCode', models.AutoField(primary_key=True, serialize=False)),
                ('CatalogueName', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CategoryCode', models.AutoField(primary_key=True, serialize=False)),
                ('CategoryName', models.CharField(max_length=250)),
                ('CatalogueCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.catalogue')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('DateInserted', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('ProductCode', models.AutoField(primary_key=True, serialize=False)),
                ('SKU', models.CharField(max_length=250, unique=True)),
                ('ProductName', models.TextField(blank=True)),
                ('URL', models.TextField(blank=True)),
                ('MainImage', models.TextField(blank=True, max_length=500, null=True)),
                ('CatalogueName', models.CharField(max_length=250)),
                ('CategoryName', models.CharField(max_length=250)),
                ('BrandCode', models.CharField(blank=True, max_length=255, null=True)),
                ('BrandName', models.CharField(blank=True, max_length=255)),
                ('Currency', models.CharField(max_length=100)),
                ('About', models.TextField(blank=True, default='', null=True)),
                ('StockAvailability', models.BooleanField(default=True)),
                ('Offer', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('RegularPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ModelNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('RatingValue', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('CatalogueCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.catalogue')),
                ('CategoryCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('DateInserted', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('VendorCode', models.AutoField(primary_key=True, serialize=False)),
                ('VendorName', models.CharField(max_length=250)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255)),
                ('Comment', models.TextField()),
                ('Source', models.CharField(blank=True, max_length=255)),
                ('CommentDate', models.DateField()),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('max_rating', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='VendorCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vendor'),
        ),
        migrations.CreateModel(
            name='OurStoreProduct',
            fields=[
                ('DateInserted', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('ProductCode', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=250)),
                ('SKU', models.CharField(max_length=250, unique=True)),
                ('URL', models.TextField(blank=True, null=True)),
                ('MainImage', models.TextField(blank=True, max_length=500, null=True)),
                ('BrandName', models.CharField(blank=True, max_length=255)),
                ('Currency', models.CharField(max_length=100)),
                ('About', models.TextField(blank=True, default='', null=True)),
                ('StockAvailability', models.BooleanField(default=True)),
                ('Offer', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('RegularPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=19, null=True)),
                ('ModelNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('RatingValue', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('CatalogueName', models.CharField(max_length=255)),
                ('CategoryName', models.CharField(max_length=255)),
                ('CatalogueCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.catalogue')),
                ('CategoryCode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255)),
                ('image_url', models.TextField(blank=True)),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryNameMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateInserted', models.DateTimeField(auto_now_add=True, null=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('CategoryName', models.TextField()),
                ('CategoryCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('VendorCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.vendor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=255)),
                ('AdditionalProperty', models.TextField()),
                ('ProductCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
