# Generated by Django 4.2.16 on 2024-09-06 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ourstoreproduct',
            old_name='Offer',
            new_name='Cost',
        ),
        migrations.RenameField(
            model_name='ourstoreproduct',
            old_name='RegularPrice',
            new_name='MyPrice',
        ),
    ]
