# Generated by Django 4.2.16 on 2024-09-19 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalproperty',
            name='SKU',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='CatalogueName',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryName',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='SKU',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourstoreproduct',
            name='BrandName',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourstoreproduct',
            name='CatalogueName',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourstoreproduct',
            name='CategoryName',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourstoreproduct',
            name='ModelNumber',
            field=models.CharField(db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ourstoreproduct',
            name='ProductName',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ourstoreproduct',
            name='SKU',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='ourstoreproductattribute',
            name='AttributeName',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ourstoreproductattribute',
            name='AttributeValue',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='BrandCode',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ModelNumber',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.TextField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(db_index=True, max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='AttributeName',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='AttributeValue',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='review',
            name='SKU',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='VendorName',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AddIndex(
            model_name='ourstoreproduct',
            index=models.Index(fields=['SKU', 'CategoryCode', 'BrandName'], name='product_our_SKU_27ec7c_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['SKU', 'CategoryCode', 'VendorCode'], name='product_pro_SKU_e139ed_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['ProductName'], name='product_pro_Product_f58116_idx'),
        ),
    ]
