# Generated by Django 4.2.16 on 2024-09-24 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_additionalproperty_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstoreproduct',
            name='ModelName',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='ModelName',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
