# Generated by Django 3.0.4 on 2024-03-27 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20240326_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='BestRating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ModelName',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ProductDesc',
        ),
        migrations.RemoveField(
            model_name='product',
            name='ReviewCount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='SubBrandName',
        ),
    ]
