# Generated by Django 3.0.4 on 2024-03-28 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20240327_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MainImage',
            field=models.TextField(blank=True),
        ),
    ]
