# Generated by Django 4.2.16 on 2024-09-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_ourstoreproduct_modelname_product_modelname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourstoreproduct',
            name='Market',
            field=models.CharField(default='UAE', max_length=100),
            preserve_default=False,
        ),
    ]
