# Generated by Django 3.0.4 on 2024-04-02 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20240329_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='URL',
            field=models.TextField(blank=True),
        ),
    ]
