# Generated by Django 3.0.4 on 2024-04-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20240402_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='Source',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
