# Generated by Django 3.0.4 on 2024-04-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20240403_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ProductName',
            field=models.TextField(blank=True),
        ),
    ]
